development:
  adapter: postgresql
  encoding: unicode
  database: ENV['DATABASE_NAME']
  host: ENV['DATABASE_HOST']
  username: ENV['DATABASE_USER']
  password: ENV['DATABASE_PASSWORD']
  port: ENV['DATABASE_PORT']
production:
  adapter: postgresql
  encoding: unicode
  database: ENV['DATABASE_NAME']
  pool: ENV['DATABASE_PORT']
  host: ENV['DATABASE_HOST']
  username: ENV['DATABASE_USER']
  password: ENV['DATABASE_PASSWORD']
  port: ENV['DATABASE_PORT']
